### ISSUE TITLE
emojis in chat messages break votes

### ISSUE THREAD

**Issue by velocinatortv** [modestimpala/VotVChaosMod#5]
as it stands when anyone in chat uses an emoji, there's a n encoding issue, and the script doesn't have a fallback to return back.

I've attached my error below.

thanks for an awesome mod, can't wait to play more 

`2024-11-04 23:10:05,292 - __main__ - INFO - Starting ChaosBot
2024-11-04 23:10:05,293 - __main__ - INFO - Loading config
2024-11-04 23:10:05,295 - __main__ - INFO - Establishing subsystems
2024-11-04 23:10:05,296 - src.twitch_connection - INFO - Initializing Twitch Connection...
2024-11-04 23:10:05,297 - __main__ - INFO - Starting Twitch Connection
2024-11-04 23:10:05,297 - src.twitch_connection - INFO - Starting Twitch Connection...
2024-11-04 23:10:06,173 - twitchio.websocket - INFO - Successfully logged onto Twitch WS: velocinator
2024-11-04 23:10:06,219 - src.twitch_connection - INFO - Logged in as | velocinator
2024-11-04 23:10:06,219 - src.twitch_connection - INFO - ChaosBot is now running...
2024-11-04 23:10:06,221 - src.twitch_connection - INFO - Use Ctrl+C to stop the bot gracefully.
Shop order processed for gussedup: crowbar
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1103, in emit
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\U000e0000' in position 432: character maps to <undefined>
Call stack:
  File "ChaosBot.py", line 149, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 633, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 600, in run_forever
  File "asyncio\base_events.py", line 1896, in _run_once
  File "asyncio\events.py", line 80, in _run
  File "twitchio\websocket.py", line 184, in _keep_alive
  File "logging\__init__.py", line 1465, in debug
  File "logging\__init__.py", line 1624, in _log
  File "logging\__init__.py", line 1634, in handle
  File "logging\__init__.py", line 1696, in callHandlers
  File "logging\__init__.py", line 968, in handle
  File "logging\handlers.py", line 75, in emit
  File "logging\__init__.py", line 1218, in emit
  File "logging\__init__.py", line 1108, in emit
Message: ' < @badge-info=;badges=twitch-recap-2023/1;client-nonce=0b64efcd57be0a08565cbbeef00749db;color=#FF0000;display-name=Clloakie;emotes=;first-msg=0;flags=;id=f94f2980-58d3-4c6c-ba5b-9e98f4a3fabd;mod=0;returning-chatter=0;room-id=70581143;subscriber=0;tmi-sent-ts=1730781128266;turbo=0;user-id=153431124;user-type= :clloakie!clloakie@clloakie.tmi.twitch.tv PRIVMSG #velocinator :4 \U000e0000\r\n'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1103, in emit
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f426' in position 413: character maps to <undefined>
Call stack:
  File "ChaosBot.py", line 149, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 633, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 600, in run_forever
  File "asyncio\base_events.py", line 1896, in _run_once
  File "asyncio\events.py", line 80, in _run
  File "twitchio\websocket.py", line 184, in _keep_alive
  File "logging\__init__.py", line 1465, in debug
  File "logging\__init__.py", line 1624, in _log
  File "logging\__init__.py", line 1634, in handle
  File "logging\__init__.py", line 1696, in callHandlers
  File "logging\__init__.py", line 968, in handle
  File "logging\handlers.py", line 75, in emit
  File "logging\__init__.py", line 1218, in emit
  File "logging\__init__.py", line 1108, in emit
Message: ' < @badge-info=;badges=moderator/1,partner/1;color=#5B99FF;display-name=StreamElements;emotes=;first-msg=0;flags=;id=c2637c88-f430-4c1f-af1e-23fd2999a8a3;mod=1;returning-chatter=0;room-id=70581143;subscriber=0;tmi-sent-ts=1730781165114;turbo=0;user-id=100135110;user-type=mod :streamelements!streamelements@streamelements.tmi.twitch.tv PRIVMSG #velocinator :🐦 TWITTER: https://www 🟥 YOUTUBE: https://www.youtube.com/ 🟪 DISCORD: https://discord.gg/ 📸 INSTAGRAM: https://www.instagram.com/ 🧵 https://www.threads.net/\r\n'
Arguments: ()
`

**Comment by modestimpala** [comment]
Hi velocinator, 
Just now got around to this, been very busy irl lately. I appreciate you taking the time to report this issue! 

I've got this fixed in a commit I'm about to push and I'll try to get a new EXE file out soon.
There is a decent update in the works and this fix will be added to that branch.

Regards,
Moddy
